services:
  php:
    image: php:8.1-cli
    container_name: php_server
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - '8080:80'
    entrypoint:
      [
        '/bin/sh',
        '-c',
        "echo 'To access locally: http://localhost:8080' && php -S 0.0.0.0:80 -t /var/www/html",
      ]
